# Generated by Django 5.0.9 on 2024-09-22 18:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_hero_cta_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCarousels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('carousel_title', models.CharField(help_text='Carousel Title *', max_length=200, null=True)),
                ('carousel_subtitle', models.CharField(help_text='Carousel Subtitle', max_length=200, null=True)),
                ('carousel_cta', models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=255, null=True, verbose_name='Carousel CTA')),
                ('carousel_cta_url', models.URLField(blank=True, help_text='If carousel_cta_link not found. Then this url work', verbose_name='Carousel URL')),
                ('carousel_cta_link', models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
                ('carousel_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_carousels', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
