# Generated by Django 5.0.9 on 2024-09-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
    ]
